import type { Metadata } from "next"
import { PageHeader } from "@/components/page-header"
import { PageNav } from "@/components/page-nav"
import { PageShell } from "@/components/page-shell"
import { ComponentPreview } from "@/components/component-preview"
import styles from "@/components/scroll-snap-demo.module.css"

export const metadata: Metadata = {
  title: "Scroll Snap",
}

const galleryCss = `/* The scroll container sets the snap axis + strictness */
.gallery {
  display: flex;
  gap: 1rem;
  overflow-x: auto;
  scroll-snap-type: x mandatory;
  scroll-padding: 0.25rem;
}

/* Each child declares where it comes to rest */
.slide {
  scroll-snap-align: center;
  scroll-snap-stop: always;
  flex: 0 0 min(20rem, 80%);
  height: 14rem;
}`

const galleryHtml = `<div class="gallery">
  <div class="slide"><span>01</span><h3>Snap start</h3></div>
  <div class="slide"><span>02</span><h3>Snap center</h3></div>
  <div class="slide"><span>03</span><h3>Snap always</h3></div>
  <div class="slide"><span>04</span><h3>No JS</h3></div>
</div>`

const sectionCss = `/* A scrollable viewport that snaps to full panels */
.viewport {
  height: 22rem;
  overflow-y: auto;
  scroll-snap-type: y mandatory;
}

/* Each panel fills the viewport and snaps to the top */
.panel {
  scroll-snap-align: start;
  scroll-snap-stop: always;
  height: 22rem;
}`

const sectionHtml = `<div class="viewport">
  <section class="panel"><h3>First</h3></section>
  <section class="panel"><h3>Second</h3></section>
  <section class="panel"><h3>Third</h3></section>
</div>`

const slides = [
  {
    index: "01",
    title: "scroll-snap-type",
    text: "The container sets the axis and strictness: x mandatory forces a rest on every slide.",
  },
  {
    index: "02",
    title: "scroll-snap-align",
    text: "Each child decides where it lands — start, center, or end of the scrollport.",
  },
  {
    index: "03",
    title: "scroll-snap-stop",
    text: "always prevents fast flicks from skipping past a slide, one card at a time.",
  },
  {
    index: "04",
    title: "No JavaScript",
    text: "The browser handles the momentum, easing, and resting position for free.",
  },
]

const carouselCss = `/* The scroll container generates its own buttons + dots */
.carousel {
  display: flex;
  overflow-x: auto;
  scroll-snap-type: x mandatory;
  scroll-behavior: smooth;
  scroll-marker-group: after; /* where the dots render */
}

.slide {
  scroll-snap-align: center;
  scroll-snap-stop: always;
  flex: 0 0 100%;
}

/* Prev / next buttons — generated by the browser */
.carousel::scroll-button(left)  { content: "\\2039"; }
.carousel::scroll-button(right) { content: "\\203A"; }
.carousel::scroll-button(*):disabled { opacity: 0.35; }

/* The dot marker group + one dot per slide */
.carousel::scroll-marker-group { display: flex; gap: 0.5rem; }
.slide::scroll-marker {
  content: "";
  width: 0.6rem;
  height: 0.6rem;
  border-radius: 999px;
  border: 1px solid gray;
}

/* Highlight the dot for the slide currently in view */
.slide::scroll-marker:target-current {
  background: dodgerblue;
}`

const carouselHtml = `<div class="carousel">
  <div class="slide">Slide 01</div>
  <div class="slide">Slide 02</div>
  <div class="slide">Slide 03</div>
  <div class="slide">Slide 04</div>
</div>`

const carouselSlides = [
  { index: "01", title: "Generated buttons", text: "::scroll-button(left) and ::scroll-button(right) render real, focusable controls." },
  { index: "02", title: "Generated markers", text: "scroll-marker-group plus ::scroll-marker give you dot navigation for free." },
  { index: "03", title: "Active state", text: ":target-current highlights the dot for whichever slide is in view." },
  { index: "04", title: "Zero JavaScript", text: "No event listeners, no state, no libraries — the scroll container owns it all." },
]

const panels = [
  {
    kicker: "Panel 01",
    title: "Full-height snapping",
    text: "A vertical container with scroll-snap-type: y mandatory brings each section to rest at the top of the viewport.",
  },
  {
    kicker: "Panel 02",
    title: "One at a time",
    text: "scroll-snap-stop: always makes sure each panel gets its moment — a single scroll gesture advances exactly one panel.",
  },
  {
    kicker: "Panel 03",
    title: "Native and smooth",
    text: "Pair it with scroll-behavior: smooth and the browser does the rest. No libraries, no scroll listeners.",
  },
]

export default function ScrollSnapPage() {
  return (
    <PageShell>
      <PageHeader
        eyebrow="CwS 1.0"
        title="Scroll Snap"
        description="CSS scroll snapping lets a scroll container lock onto its children as you scroll. The container declares scroll-snap-type, each child declares scroll-snap-align — and the browser handles the rest, with no JavaScript."
      />

      <div
        className="mt-8 rounded-lg border p-4 text-sm leading-relaxed"
        style={{
          borderColor: "color-mix(in oklab, #eab308 45%, transparent)",
          background: "color-mix(in oklab, #eab308 12%, var(--background))",
          color: "color-mix(in oklab, #eab308 35%, var(--foreground))",
        }}
      >
        <strong style={{ color: "#eab308" }}>{"// Heads up"}</strong>{" "}
        The CSS-only carousel below uses the new <code>::scroll-button()</code> and{" "}
        <code>::scroll-marker</code> pseudo-elements. These are newly available — check{" "}
        <a
          href="https://developer.mozilla.org/en-US/docs/Web/CSS/::scroll-marker"
          target="_blank"
          rel="noreferrer"
          style={{ color: "#eab308", textDecoration: "underline" }}
        >
          browser support
        </a>{" "}
        before relying on them in production. Scroll snapping itself (the other two examples) is fully supported.
      </div>

      <div className="mt-10 flex flex-col gap-12">
        <ComponentPreview
          title="Horizontal gallery"
          description="Scroll or swipe sideways — the container snaps each card to center. Try a fast flick: scroll-snap-stop: always stops one card at a time."
          html={galleryHtml}
          css={galleryCss}
        >
          <div className={styles.gallery}>
            {slides.map((slide) => (
              <article key={slide.index} className={styles.slide}>
                <span className={styles.slideIndex}>{slide.index}</span>
                <h3 className={styles.slideTitle}>{slide.title}</h3>
                <p className={styles.slideText}>{slide.text}</p>
              </article>
            ))}
          </div>
        </ComponentPreview>

        <ComponentPreview
          title="CSS-only carousel"
          description="Prev/next buttons and dot markers with zero JavaScript. The container generates the controls with ::scroll-button() and ::scroll-marker — try the arrows, the dots, or a swipe."
          html={carouselHtml}
          css={carouselCss}
        >
          <div className={styles.carouselWrap}>
            <div className={styles.carousel}>
              {carouselSlides.map((slide) => (
                <article key={slide.index} className={styles.carouselSlide}>
                  <span className={styles.slideIndex}>{slide.index}</span>
                  <h3 className={styles.slideTitle}>{slide.title}</h3>
                  <p className={styles.slideText}>{slide.text}</p>
                </article>
              ))}
            </div>
          </div>
        </ComponentPreview>

        <ComponentPreview
          title="Vertical section snap"
          description="Scroll inside the frame — each full-height panel snaps to the top of the viewport, the pattern behind full-page scrolling sites."
          html={sectionHtml}
          css={sectionCss}
        >
          <div className={styles.viewport}>
            {panels.map((panel) => (
              <section key={panel.kicker} className={styles.panel}>
                <span className={styles.panelKicker}>{panel.kicker}</span>
                <h3 className={styles.panelTitle}>{panel.title}</h3>
                <p className={styles.panelText}>{panel.text}</p>
              </section>
            ))}
            <p className={styles.hint} aria-hidden="true">
              Keep scrolling ↑↓
            </p>
          </div>
        </ComponentPreview>
      </div>

      <PageNav />
    </PageShell>
  )
}
